### ISSUE TITLE
[ObjTiler] Creating tiles with a refinement hierarchy

### ISSUE THREAD

**Issue by vladimir-rybalko** [VCityTeam/py3dtilers#106]
Hi all!

I'm trying to get 3D tiles to display from an obj file with a texture. I am running the following command
`obj-tiler --loa --paths <obj_in_path> --with_texture --crs_in EPSG:32660 --crs_out EPSG:4978  --output_dir <tilesets_3d_out_path>`
But as a result I get only one tile. How do I get a set of tiles with a refinement hierarchy?
![image](https://user-images.githubusercontent.com/3933179/185110037-73da70e5-3a8c-49e0-a12f-9b4039fefdef.png)

**Comment by LorenzoMarnat** [comment]
Hello

If you want a refinement hierarchy, you can use both [`--lod1` and/or `--loa` flags](https://github.com/VCityTeam/py3dtilers/blob/master/docs/Doc/Tilers_features.md#levels-of-detail). Usage notes can be found [here](https://github.com/VCityTeam/py3dtilers/tree/master/py3dtilers/Common#loa) and more details can be found [here](https://github.com/VCityTeam/py3dtilers/tree/master/py3dtilers/Common#lod_tree).

In order to use `--loa`, you need a GeoJSON file which contains polygons or multipolygons. Those polygons will be used to create the level of abstraction: all the objects contained in the same polygon will be represented by the extrusion of this polygon.

Note that the ObjTiler currently __can't split an OBJ mesh in different tiles__: the entire mesh will be in the same tile. In order to obtain different tiles, you need either different OBJ files or different meshes in an OBJ file.

Example:

If you have some OBJ files and a GeoJSON file (with the same projection)

```json
{
    "type": "FeatureCollection",
    "name": "polygon",
    "crs": {
        "type": "name",
        "properties": {
            "name": "urn:ogc:def:crs:EPSG::3946"
        }
    },
    "features": [
        {
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "MultiPolygon",
                "coordinates": [
                    [
                        [
                            [1843117.999617710942402,5174370.103565665893257],[1843124.035103792324662,5174367.352734769694507],[1843103.927815038710833,5174323.99722246080637],[1843068.914649155922234,5174339.84542538318783],[1843071.488959094043821,5174341.046143365092576],[1843072.284143022960052,5174341.481833869591355],[1843114.851368357194588,5174368.529441232793033],[1843117.999617710942402,5174370.103565665893257]
                        ]
                    ]
                ]
            }
        }
    ]
}
```

You can create an LOA with:

```bash
obj-tiler --paths obj_buildings --loa polygon.geojson  [other options...]
```
