### ISSUE TITLE
Installing error in Window10

### ISSUE THREAD

**Issue by 3DGISKing** [VCityTeam/py3dtilers#121]
`pip install -e . -v` gives following error

![image](https://user-images.githubusercontent.com/26606704/210052391-64cd1ace-e149-42c5-9d4e-6aa4caec75c0.png)

**Comment by clementcolin** [comment]
You got this error because the ifcopenshell library originally could not be installed using pip.

You can try and use the branch [ifcopenshell](https://github.com/VCityTeam/py3dtilers/tree/ifcopenshell) that should fix your problem. The ad-hoc pr #114  should be merged very soon in the master branch.

**Comment by LorenzoMarnat** [comment]
Hello,

You have this error because pip can't find a version of [IfcOpenShell](https://github.com/IfcOpenShell/IfcOpenShell) for Python 3.11.

We recommend to install and use __Python 3.9__ to install Py3DTilers without trouble:

```bash
python3.9 -m venv venv
. venv/Scripts/activate
(venv)$ pip install -e .
```

The IfcOpenShell is used only by the IFC Tiler (IFC to 3D Tiles). So, if you want to use Python 3.11 and don't need the IFC Tiler, you can comment the IfcOpenShell line in [setup.py](https://github.com/VCityTeam/py3dtilers/blob/master/setup.py#L23) and run the installation again.
