### ISSUE TITLE
Cleanup/converge old documentation

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/py3dtilers#15]
Merge [old documentation](https://github.com/VCityTeam/py3dtilers/blob/master/Doc/CityTilerUsage.md) with up to date pipeline [readme](https://github.com/VCityTeam/py3dtilers/blob/CityTiler_with_LodTree/py3dtilers/CityTiler/README.md)

In particular, please document the `junk*` output folder for new users

**Comment by LorenzoMarnat** [comment]
The documentation is now up to date on master branch in the [CityTiler's readme](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/CityTiler/README.md) (since [the rework](https://github.com/VCityTeam/py3dtilers/pull/12) has been accepted).  
I also added [few lines](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/CityTiler/README.md#run-the-citytiler) about the junk output folder in the CityTiler readme
