### ISSUE TITLE
Remove hardwired geographical coordinates system code

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/py3dtilers#5]
Within `IfcTiler/ifcObjectGeom.py` code like
```
transformer = Transformer.from_crs("EPSG:27562", "EPSG:3946")
```
hard-wires 
 - the knowledge projection system of the input data (we could have another system for the input)
 - the projection system of the resulting 3dTiles output (the user might like to specify another projection system)
 
Such a rewriting/conversion should be within the Tiler but outside of it. Let the Tiler produce a 3dTiles using the projection system of it's input. Then write a 3dTiles converter utility (CLI) that converts the projection system. This would [separate the concerns](https://en.wikipedia.org/wiki/Separation_of_concerns).

**Comment by clementcolin** [comment]
In order to write a clean 3DTiles converter utility, there is some work to be done in py3dtiles first. 
Indeed, there is currently no 3DTiles (tileset.json) reader : 
- only tiles reader exist [here](https://github.com/VCityTeam/py3dtiles/blob/Tiler/py3dtiles/utils.py#L15) and used [here](https://github.com/VCityTeam/py3dtiles/blob/Tiler/py3dtiles/info.py)
- the current [tileset class](https://github.com/VCityTeam/py3dtiles/blob/Tiler/py3dtiles/tileset.py) only allows to write a tileset but not to read from one

Once we are able to read a tileset, we should then be able to modify it, i.e, in this case, change the projection system used.

**Comment by EricBoix** [comment]
Concerning the 3dtiles deserialization process refer to [this issue](https://github.com/VCityTeam/py3dtiles/issues/15).

**Comment by LorenzoMarnat** [comment]
[This PR](https://github.com/VCityTeam/py3dtilers/pull/27) introduce `crs_in` and `crs_out` flags. The `crs_in` flag allows to specify the input CRS (default is EPSG:3946). The `crs_out` flag projects the geometries in another CRS (default output CRS is EPSG:3946). Those flags can be used by __any tiler__ inheriting from [Tiler class](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/Common/tiler.py#L90).

Example with the IfcTiler

```bash
ifc-tiler path/to/ifc --crs_in EPSG:4171 --crs_out EPSG:3946
```
