### ISSUE TITLE
Reduce memory footprint of CityTiler by working tile by tile?

### ISSUE THREAD

**Issue by jailln** [VCityTeam/py3dtilers#58]
I think we could reduce the memory footprint of the CityTiler by working tile by tile instead than with the entire tileset at once and therefore scale up to converting big datasets.

From what I understand, the current main steps of the `CityTiler` are:
* Retrieve city objects from the database (just the metadata, not the geometry nor the texture) in [retrieve_objects()](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/CityTiler/citym_cityobject.py#L86)
* Retrieve geometries (and textures) in [get_surfaces_with_texture()](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/CityTiler/CityTiler.py) (same process without textures)
* Create the tileset in [create_tileset_from_geometries()](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/Common/tiler.py#L84):
  * scale, translate and reproject geometries
  * create the tree structure (one of):
    * kd tree (only uses the centroid of the cityobjects and not the geometries) + create lods (optional) (uses geometries) 
    * create loa (only uses cityobjects centroid)
  * create and write textures atlases on disk (tile by tile) (optional)
  * create all tiles and tiles contents
* write the full tileset (geometry and attributes) on disk

I propose the following workflow:
* Retrieve city objects (just the metadata, not the geometry nor the texture) and their centroid from the database
* create the tree (one of):
  * kd-tree + one prepare one LOD level in the tree (without actually computing this LOD)
  * loa
* Tile by tile:
  * load geometries and textures
  * scale, translate and reproject geometries
  * create and write texture atlas on disk
  * create the lod tiles content (optional)
  * create and write tiles and tiles contents on disk

What do you think ? Could this proposal not be possible due to other tilers or other processes that I missed ?

**Comment by LorenzoMarnat** [comment]
> From what I understand, the current main steps of the CityTiler are:

That's absolutely the current steps of the CityTiler (and of all Tilers).

> What do you think ? Could this proposal not be possible due to other tilers or other processes that I missed ?

It's a really good idea, this will drastically reduce the memory usage of the CityTiler. This workflow may be more complicated to implement for other Tilers, since (with OBJs, IFCs or GeoJSON features) we need to load a geometry to compute its centroid.

But, in a first time, we could load in memory only the metadata/centroids for the cityTiler but load everything in memory with the other Tilers, and then create the tileset tile by tile. The only difference would be that, during the tile creation, the geometries will be loaded from the database for the cityTiler, while beeing already in memory for the other Tilers.

I'll take some time to evaluate the difficulty/time of such a refacto, and see how to integrate it into the roadmap.

**Comment by jailln** [comment]
> But, in a first time, we could load in memory only the metadata/centroids for the cityTiler but load everything in memory with the other Tilers, and then create the tileset tile by tile. The only difference would be that, during the tile creation, the geometries will be loaded from the database for the cityTiler, while beeing already in memory for the other Tilers.

Yep that's a good idea. If the same problem happens for other tilers that need the geometry to compute the centroid, a possibility would be to load geometries in batches small enough to avoid ram overload. But let's wait for the problem to happen before solving it because like @EricBoix says: it works, don't fix it :grinning: 

> I'll take some time to evaluate the difficulty/time of such a refacto, and see how to integrate it into the roadmap.

Thanks, don't hesitate to share that analysis and the different steps that you foresee here.

**Comment by clementcolin** [comment]
In order to change the workflow, we should at least need for each type a method to : 
- Get the centroid of an object
- Get the geometry from the source
- Get the texture (if needed) from the source
instead of doing all of those in once. 
They need to be explicitly described in the ObjectToTile (or TilableInterface) first.

> a possibility would be to load geometries in batches small enough to avoid ram 

I completely agree with this statement, because, even with a workflow were we only load the geometry of a tile at a time, we may still have this memory footprint problem, as we currently split a tile only when meeting a certain abritary amount of Feature per tile, 500 according to this [line](https://github.com/VCityTeam/py3dtilers/blob/bc6562034190ad36437ad5720973098715baddce/py3dtilers/Common/group.py#L112)`objects = kd_tree(self.objects_to_tile, 500)`. We do not take into account the size of each geometry/ texture of the features.

To solve this, the atlas texture size and the geometry size of a tile can be used to create the tileset tree. However, to achieve such a feature, we need to keep track of the current tile memory size (of both texture and geometry) during its computation, and split the tile if needed.

**Comment by jailln** [comment]
Yes we should indeed also consider using other indicators than the number of objects to create the tree, e.g the number of triangle, textures size or objects bounding boxes, since currently all objects are considered equivalent in complexity (number of triangles, textures size, etc.) while they are unlikely to be. It would consist in constructing the kd-tree based on a number of triangles and/or the size of the textures per tile (but without separating objects in multiple tiles). This would also have the benefit to construct a tree with more consistent tiles (in terms of the number of triangles and texture size). However, I wonder if such a tree would be more efficient than a quadtree constructed with the same criteria (number of objects, number of triangles, texture size). Anyway, working tile by tile should resolve the memory overload problem in most cases I think.

**Comment by LorenzoMarnat** [comment]
Work in progress on [city_tiler_tile_by_tile](https://github.com/VCityTeam/py3dtilers/tree/city_tiler_tile_by_tile) branch

Create the tileset by loading the geometrie/textures tile by tile. The geometries/textures of a tile are destroyed after the tile is created. The CityTiler only loads the centroid of each feature to create the GeometryTree (kd_tree, LODs, etc).

This way, the CityTiler memory usage goes up to ~800 Mo (vs ~3 Go in current implementation) for all buildings of all Lyon's boroughts. The memory slightly increases over time because the tiles are kept in memory and the whole tileset is writen on disk at once.

Translation, reprojection, scaling and writing as OBJ should work correctly. There might be some issues with LODs. The other Tilers still load all the geometries before the tileset creation.

**Comment by LorenzoMarnat** [comment]
Done in [this PR](https://github.com/VCityTeam/py3dtilers/pull/71)
