### ISSUE TITLE
[CityTiler] Tiling with textures creates many more tiles

### ISSUE THREAD

**Issue by jailln** [VCityTeam/py3dtilers#65]
Running the city tiler with the `--with-texture` option results in a tileset with a lot more tiles. From my tests, from 32x to 64x more tiles are generated with the `--with-texture` option for the same input dataset. Do you know where this come from and if it is an intended behavior ?

I think this has an impact on the tileset size and on the visualization performances.

**Comment by jailln** [comment]
Thanks for the precision. I agree with both solutions (that seems complementary). We could also add a third one: actually use the number of features to create a tile when tiling with textures (and not the number of surfaces) even if the features are split for texturing (this probably means keeping a list of initial objects and a link to their surfaces). I think this would make more sense with a `kd_tree` based on a number of features per tile since features are usually defined according to their semantics for this type of data (citygml): e.g. we refer to a building, a bridge, a roof, etc. and so it is easier to create a tileset with n features per tile than with n surfaces per tile IMO (at least until other ways of limiting tiles size are used as proposed in your second item). Doing so would also avoid having "semantically defined" features (e.g. buildings, bridges) scattered across multiple tiles.

**Comment by LorenzoMarnat** [comment]
With [tile by tile PR](https://github.com/VCityTeam/py3dtilers/pull/71), the features are split into surfaces __after__ the kd-tree distribution. Also, the [kd-tree max PR](https://github.com/VCityTeam/py3dtilers/pull/85) allows to choose the number of features per tile. So, we will always put n features per tile (instead of n surfaces).

By default, each tile can contain 500 features (max). When creating a textured tileset, this default value is divided by 20 to reduce the size of the texture atlases. So, creating a textured tileset will still create more tiles than a non-textured tileset. The user can choose to create tiles of 500 textured features by using `--kd_tree_max 500`.

Work will be done to [reduce the size (in memory) of textured tiles](https://github.com/VCityTeam/py3dtilers/issues/73) and to [compress the images/geometries](https://github.com/VCityTeam/py3dtilers/issues/46).
